name: ci

on: push

env:
  AWS_REGION: us-east-1

jobs:
  validate:
    runs-on: ubuntu-latest
    env:
      CFN_TEMPLATES: ".github/cd_setup.yml\n"
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: validate all cloudformation templates
        run: |
          printf "${{ env.CFN_TEMPLATES }}" | while read template; do
            aws cloudformation validate-template \
              --template-body="file://$template"
          done

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: clone the repo
        uses: actions/checkout@v2.3.4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.5.3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: test ecs-ami command line tool
        run: |
          chmod +x ./get_ecs_ami_map.sh
          ./get_ecs_ami_map.sh amazon-linux
          ./get_ecs_ami_map.sh amazon-linux-2
          ./get_ecs_ami_map.sh amazon-linux-2 arm64
          ./get_ecs_ami_map.sh amazon-linux-2 inf
          ./get_ecs_ami_map.sh amazon-linux-2 gpu
